language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - MODULE_DIR=SlackLogger

install:
  - pip install .
  - pip install pylint

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pylint --errors-only $MODULE_DIR

after_success:
  - python setup.py sdist bdist_wheel

jobs:
  include:
    - stage: deploy
      script: skip
      python: 2.7
      deploy:
        provider: pypi
        user: Greums
        password:
          secure:   0lZgFXsELeiRGwxmqVejBLdqTVqwRFg2eZte6jWY8ekHKRjkUcAXOAshnO7Y3fvbu6zONdeR9Wat2dk5i3Sh450ehz0zGn1E7V2IgcckjXvyuQun9PS39NlqSJSvjmgs9xl9qi4Okx8Tx9kpnKvkv7ihTS8BxX1uj44AvcMn43mwERShUKfkzyhrHjdXGVcLBBsDksntk7sKzTJmAiJHY9YTT6giixWWXY4AZEaLitgcHE6siFJVshRmP724XGXjU+BjsVVBulhGJpwS4bU3NFMqwnKkzulVSqR8UBj4C82u9oy1TGS6lg0XJGH8qQh7OZZiIJmMJa/TnuOGoH0Jct9+hj7m9XESwCUNXKUICzRtrDR9GwKWw1sF0tcbLkSrW+bzMRPW6IUJpd6ROZ9oTbaQ3vs8oacE///S+I8/3qHEEvSV+9m71SbjGsLM8mGHLt7tobH0sGGQKAPoxJ3JuZmZPMVHD1MdsSfIWAproSqZXELJ+BfatRAici7MPljb3pNnzbuHoj6yP4oHo9RO4Vda5nqEjjRtoFXe1t4kZMAUh3ebRoSlOFeErBCc4i1rYskjGrVjyrALHzxzOAkv1zG4dx0Zp1eokk8d0kVw/6dhiU2/RxJLuM1AuqBes/CyTUfyGoAIQRoLSr89hH2wCb+RWFzqSnveFRpksAN/V28=
        on:
          tags: true
          branch: master
        distributions: sdist bdist_wheel
      skip_cleanup: true

notifications:
  slack:
    secure: KYm6oAFn5bblkbpZ3Q5u66PWCmoof8UNHkNx8uI0owgJ2mnTq5L9YVW130tjia/MOqryCENMGlURC8F6v5wzNSr2A5hEBwGnrDL8aZIN82wvaQT130HDFbg0H8br3s6pV+eRRbyvkAhoEnTNegcWbwlLlEUTYKKMeLlfh3fICZ6Ul9uaINSjfk2qbStGkqnVcs+t43fK8UxrTQmJCSbrHOLdFNlyH0vFjEaK8qf7+LYa+kT041+KYB1ZxtOz/5pnpH/dLih24PUK/wlr0yrkbjbhWp/vTHXUb4LfewifyDULiw9AlsfsIPi2jgsNGn+Jz/zc53WN/tgkV/0uJCoWgmpt/u1IM+Y+JwHDNPqo/BHO4odw9H9ZpayvOfj8ZljbDiqn/06O+sT32MVRrnApGfQu1oWDRMyQGvzMSLM6zyX9Xs4CcdXovdCA5hBzfRrXoc40VMyxaqAw9PZy9TRWKl+FM5tdABcIKZN4qcujfvP3cOTdL6C3KrKely7nwougKYne5OgaGCbu1MGwL5wu3px4p6R7O/bt/6vHZ5HiXStG5sohiQ+LgeAQP7x7IWBaRNaePljgk/DMErHAZMVPFOKKPcrK577FBsjTJwUvG3so6gB9ahRhceDo8yk7c8N4yjB/GQEkHlBTIZ/trYUJceNsYFxwy37R58/IdMPIiyo=
